# Usando a imagem base do PostgreSQL
FROM postgres:13

# Variáveis de ambiente para o banco de dados
ENV POSTGRES_USER=usuario
ENV POSTGRES_PASSWORD=senha
ENV POSTGRES_DB=banco_de_dados

# Expor a porta do PostgreSQL (5432)
EXPOSE 5432
