name: Build and Test Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build Frontend Docker Image
      run: |
        cd frontend
        docker build -t frontend .

    - name: Run Frontend Tests
      run: |
        docker run frontend npm test

  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build Backend Docker Image
      run: |
        cd backend
        docker build -t backend .

    - name: Run Backend Tests
      run: |
        docker run backend npm test

  database:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build Database Docker Image
      run: |
        cd database
        docker build -t database .
