name: Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend Docker Image
      run: |
        cd frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Build and Push Backend Docker Image
      run: |
        cd backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

    - name: Build and Push Database Docker Image
      run: |
        cd database
        docker build -t ${{ secrets.DOCKER_USERNAME }}/database:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/database:latest

    - name: Simulate Production Deploy
      run: echo "Deploying to production (simulated)"
